### ISSUE TITLE
mode FetchHistory Error

### ISSUE THREAD

**Issue by htnlabs** [Lukas-Gelbmann/CryptocurrencyTradingBot#1]
Hi, congratulations on your tool. I'm testing it and enjoying it.
I'm having problems with fetchHistory mode:

```
downloading...
[]
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    framework.what_to_start()
  File "/home/CryptocurrencyTradingBot/framework.py", line 265, in what_to_start
    self.fetch_history()
  File "/home/CryptocurrencyTradingBot/framework.py", line 123, in fetch_history
    last_timestamp = history[-1][0]
IndexError: list index out of range
```

What can it be?

**Comment by htnlabs** [comment]
Adjusted. Thanks
